name: oila_market
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_layout_grid: ^2.0.8
  cached_network_image: ^3.4.1
  provider: ^6.0.5
  lottie: ^3.2.0
  floor: ^1.5.0
  sqflite: ^2.3.2
  flutter_bloc: ^9.1.1
  query: ^2.2.0
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/  
